### ISSUE TITLE
Extension Error "Copy", setting properties to "Copy"

### ISSUE THREAD

**Issue by philippinedeveloper** [philippinedeveloper/RapuAi2#3]
For some reason, the copy block receives an error when doing this:
<img width="633" alt="blocks" src="https://github.com/user-attachments/assets/3e22066a-4b01-41f3-b9f1-bf254b786f84" />

In order to fix it, I removed the GetComponent block:
![blocks (1)](https://github.com/user-attachments/assets/52f5054f-965c-49ed-9792-c004993e6c45)

This is a bug that won't be fix, I tried fixing it doesn't work.

Did not remove the Rapu.Copy block

The copy block will create a dictionary of every component on-screen, the key is the component name while the value is the component's class. The Copy block will then create an instance of it. So when I noticed the error I removed that block & It got fixed. When I click Copy. Its just a button (a some sort of replica) of the Copy button, except that it doesn't have a text, doesn't have background color (uses default background color just like the Copy button), no text color & no font size. Just a blank button.

**Comment by bextdev** [comment]
This issue is locked as resolved, you can use the solution that only results to a blank button/instance of a button that is just completely blank. Or you can use the Create block by putting your VerticalArrangement, what component name you want & ID. Then use GetComponent by joining the text of your component name & id. Don't label me as "Sleepy Extension Developer" because I always fix every issue of this extension. Closing.

**Comment by bextdev** [comment]
The bug will be resolved in V1.5, Thank You :)
